CREATE TABLE pk(
 id INT PRIMARY KEY, -- PRIMARY KEY IS USED TO MAKE THE VALUES UNIQUE AND NOT NULL.
 age INT,
 name VARCHAR(30) NOT NULL,
 email VARCHAR(50) UNIQUE,
 followers INT DEFAULT 0,
 following INT DEFAULT 0,
 CONSTRAINT CHECK (age >= 13)
);

-- THERE CAN BE MANY FOREIGN KEY IN A TABLE BUT ONLY ONE PRIMARY KEY.
CREATE TABLE fk(
 id INT PRIMARY KEY,
 content VARCHAR(100),
 user_id INT,
 FOREIGN KEY (user_id) REFERENCES pk(id) -- FOREIGN KEY IS PRIMARY KEY OF ANOTHER TABLE.
);